### PR TITLE
update run-all.sh to output a graph

### PR DESCRIPTION
**Pull request by dominictarr**
I was tired of looking at text output, and wanted to learn more about svg
so a made a little thing to output a svg graph... unfortunately I can't paste it here because it turns out github issues dont support svg. I've since learned that svg is kind of a pain in browsers!

but you can see it in this readme: https://github.com/dominictarr/svg-graph

### CODE REVIEW

**Comment by arj03** [comment]
Honest question, is that because it was too hard to set up bench-ssh-visualizer and sharing results in the git-ssb repo, or because you wanted to learn svg? :smile:

**Comment by dominictarr** [comment]
oh... no it was because I had forgotten about that.
and I guess because we where all obviously looking at text instead of
pictures when we were discussing performance.
where can I find the code for bench-ssb-visualizer?

**Comment by dominictarr** [comment]
oh I found it here,
`%HjUuYeXUExdxtbRP1Qg5O8zGc8ImndzviTkN3Y59ZAk=.sha256` cloning...

**Comment by arj03** [comment]
Yeah, added link to the viz tool in README and pushed that project to github. I won't push the bench-ssb-share repo here as I'd want that to stay on git-ssb out of respect for the people that post to it.

**Comment by christianbundy** [comment]
Do we still want to merge this, or should we use bench-ssb-visualizer instead?

**Comment by arj03** [comment]
My understanding is that this is solved now.

**Pull request closed without merging**
